### ISSUE TITLE
error: string is not assignable to "a litteral string"

### ISSUE THREAD

**Issue by mesqueeb** [wonderful-panda/vue-strict-prop#4]
Hi!
I'm trying this:
```
size: propType<"sm" | "lg">(String).required
```
and I get this error:

> Argument of type 'StringConstructor' is not assignable to parameter of type 'Prop<"sm" | "lg">'.
  Type 'StringConstructor' is not assignable to type '() => "sm" | "lg"'.
    Type 'string' is not assignable to type '"sm" | "lg"'.ts(2345)

Any advice much appreciated!

**Comment by wonderful-panda** [comment]
Try this

```typescript
// `p` comes from `import p from "vue-strict-prop"`

size: p.ofStringLiterals("sm", "lg").required
```

**Comment by mesqueeb** [comment]
thanks this worked!!
I opened [another issue](#6) with a question now about how to export this `p.ofStringLiterals("sm", "lg")` type so I can use it in another component to define that that's what I'm passing.
